[package]
name = "entity"
version = "0.1.0"
edition = "2021"
license = "CC0-1.0" 
workspace = ".."

[dependencies]
sea-orm = { workspace = true }
serde = { workspace = true }
utoipa = { workspace = true }
